services:
  train_notifier:
    container_name: train_notifier
    image: ghcr.io/acallejp97/train_time_retriever:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - CITY=
      - ORIGIN=
      - DESTINATION=
      - TIME_THRESHOLD=1
      - NOTIFICATION_URL=tgram://<BOT_TOKEN>/<CHAT_ID>
      - CRON_ONE_WAY=0 8 * * 2-4
      - CRON_RETURN_1=0 13 * * 2-3
      - CRON_RETURN_2=0 17 * * 4
      - TZ=Europe/Madrid
    restart: unless-stopped